### ISSUE TITLE
Función short_name en cada modelo

### ISSUE THREAD

**Issue by martinezo** [martinezo/contracts#7]
Agregar la funcion para recortar el nombre en todos los modelos

**Comment by 10141150** [comment]
se intentó anadir la funcion en cada modelo, pero se tendría que repetir la función varias ocasiones para cada campo, ya que al llamarse desde al vista se ejecuta todo el contenido de la funcion, queda pendiente preguntarle al ingeniero.

**Comment by cesar-alamilla** [comment]
La función ya quedó autorizada y se reviso que se aplique en todos los modelos.
